spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance-db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

security:
  secret-key: ${SECRET-KEY}

discord:
  client-id: ${DISCORD_CLIENT_ID}
  client-secret: ${DISCORD_CLIENT_SECRET}